name: AWS Access Keys Example

on:
  workflow_dispatch:

jobs:
  aws-job:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: "AKIAUM4G6O6NECWCWCPO"
      AWS_SECRET_ACCESS_KEY: "Hd+YBRBZmu/mXE8CoPbwknRlocQCJlclO6Ul+PL2"
      AWS_DEFAULT_REGION: "us-east-1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify AWS CLI
        run: aws --version

      - name: Test AWS credentials
        run: aws sts get-caller-identity
